title: The SILE Typesetter
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
baseurl: ""
paginate: 5
paginate_path: "blog/page:num"
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-mentions
exclude:
  - public
  - '*.toc'
permalink: /:categories/:year/:month/:slug
