name: GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  gh-pages:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Render example PDFs
        uses: sile-typesetter/sile@v0
        run: |
          find examples -name '*.sil' -execdir sile {} \;

      - name: Build Jekyll bits
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true

      - name: Build the site
        run: |
          make site JEKYLL=:

      - name: Inject CNAME
        if: ${{ github.repository == 'sile-typesetter/sile-typesetter.github.io' }}
        run: |
          make public/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
